username: ""
password: ""
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
cookie: "SESSION=NTk4ZWFkZTktMzkwNy00NjZmLWIxNGMtOGM0MDRlOTA2ZDYx"
关键词: "专利侵权"
案件类型: "" # 民事/刑事/行政/赔偿/执行
法院（地区）: "" # 
法院层级: "高级人民法院" # 最高人民法院/高级人民法院/中级人民法院/基层人民法院
审判程序: "一审" # 一审/二审/再审/复核/刑罚变更/其他
文书类型: "判决书" # 通知书/判决书/调解书/决定书/令/裁定书/其他
判决结果: "" # 未知/完全支持/部分支持/不支持/撤销/其他
判决开始时间: "" # 2023-10-10
判决结束时间: "" # 2023-10-11
strat_page: 1
end_page: 10
